quiet: False
with-expecter: True
filename: "mock_{{.InterfaceName}}.go"
dir: 'internal/mocks/{{trimPrefix .PackagePath "github.com/milvus-io/milvus/internal" | dir }}/mock_{{.PackageName}}'
mockname: "Mock{{.InterfaceName}}"
outpkg: "mock_{{.PackageName}}"
packages:
  github.com/milvus-io/milvus/internal/streamingcoord/server/balancer:
    interfaces:
      Balancer:
  github.com/milvus-io/milvus/internal/streamingnode/client/manager:
    interfaces:
      ManagerClient:
  github.com/milvus-io/milvus/internal/streamingnode/server/wal:
    interfaces:
      OpenerBuilder:
      Opener:
      Scanner:
      WAL:
  github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors:
    interfaces:
      Interceptor:
      InterceptorWithReady:
      InterceptorBuilder:
  google.golang.org/grpc:
    interfaces:
      ClientStream:
  github.com/milvus-io/milvus/internal/proto/streamingpb:
    interfaces:
      StreamingNodeHandlerService_ConsumeServer:
      StreamingNodeHandlerService_ProduceServer:
      StreamingCoordAssignmentService_AssignmentDiscoverServer:
  github.com/milvus-io/milvus/internal/streamingnode/server/walmanager:
    interfaces:
      Manager:
  github.com/milvus-io/milvus/internal/metastore:
    interfaces:
      StreamingCoordCataLog:
  github.com/milvus-io/milvus/internal/util/streamingutil/service/discoverer:
    interfaces:
      Discoverer:
      AssignmentDiscoverWatcher:
  github.com/milvus-io/milvus/internal/util/streamingutil/service/resolver:
    interfaces:
      Resolver:
  google.golang.org/grpc/resolver:
    interfaces:
      ClientConn:
  google.golang.org/grpc/balancer:
    interfaces:
      SubConn:
