- name: etcd
  docker_container: 
    name: etcd
    image: quay.io/coreos/etcd:v3.5.0
    command: "etcd -listen-peer-urls=http://{{etcd_ip}}:2380 -advertise-client-urls=http://{{etcd_ip}}:2379 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls=http://{{etcd_ip}}:2380 --listen-metrics-urls=http://{{etcd_ip}}:2381 --initial-cluster default=http://{{etcd_ip}}:2380 --data-dir /etcd"
    healthcheck:
      test: ["CMD", "wget", "-q", "--tries=1", "--spider", "http://etcd_ip:/health"]
      interval: 30s
      timeout: 20s
      retries: 3
    env:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: "1000"
      ETCD_QUOTA_BACKEND_BYTES: "4294967296"
    # volumes:
    #   - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    network_mode: "{{dependencies_network}}" #Use the network which defined as variable in Inventory.