name: Code Checker
# TODO: do not trigger action for some document file update

# This workflow is triggered on pushes or pull request to the repository.
on:
  pull_request:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'scripts/**'
      - 'internal/**'
      - 'cmd/**'
      - 'build/**'
      - '.github/workflows/code-checker.yaml'
      - '.env'
      - docker-compose.yml
      - Makefile
      - '!**.md'
      - '!build/ci/jenkins/**'
      # FIXME(wxyu): not need to run code check, update the ci-passed rules and remove these two lines
      - go.mod
      - go.sum

jobs:
  ubuntu:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Code Checker AMD64 Ubuntu 18.04
          os: ubuntu-18.04
        - name: Code Checker MacOS 11
          os: macos-11
    env:
      UBUNTU: 18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache CCache Volumes
        if: ${{  matrix.os == 'ubuntu-18.04' }}
        uses: actions/cache@v1
        with:
          path: .docker/amd64-ubuntu18.04-ccache
          key: ubuntu18.04-ccache-${{ hashFiles('internal/core/**') }}
          restore-keys: ubuntu18.04-ccache-
      - name: Cache Go Mod Volumes
        if: ${{  matrix.os == 'ubuntu-18.04' }}
        uses: actions/cache@v1
        with:
          path: .docker/amd64-ubuntu18.04-go-mod
          key: ubuntu18.04-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: ubuntu18.04-go-mod-
      - name: Code Check
        if: ${{  matrix.os == 'ubuntu-18.04' }}
        env:
          CHECK_BUILDER: "1"
        run: |
           ./build/builder.sh /bin/bash -c "make check-proto-product && make verifiers"
      - name: Code Check
        if: ${{  matrix.os == 'macos-11' }}
        run: |
          bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
          source ~/.gvm/scripts/gvm
          gvm install go1.17.2
          gvm use go1.17.2
          brew install boost libomp ninja tbb
          make check-proto-product && make verifiers